myset: set.o myset.o
	  gcc  -Wall -g -ansi -std=c99 -pedantic myset.o set.o -o myset 
myset.o: myset.c set.h
	gcc -Wall -c -ansi -std=c99 -pedantic myset.c -o myset.o
set.o: set.c set.h
	gcc -Wall -c -ansi -std=c99 -pedantic set.c -o set.o
	

