all:	assambler.h 
	gcc -ansi -Wall -pedantic -std=c99 -g assambler.h main.c assambler.c filework.c line.c lists.c macroTabael.c symbolTab.c  creatData.c binariTab.c machincode.c preAsammbler.c lexer.c  syntax_analiz.c firstRun.c secondRun.c memmory.c -o prog
